[Icon Theme]
Name=NEUX
Comment=Icon theme for AURES NEUX
Example=folder
Inherits=Adwaita


# KDE Specific Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,72,96,128
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16
PanelDefault=32
PanelSizes=16,22,32,48,64,72,96,128

# Directory list
Directories=symbolic/status,symbolic/devices,scalable/apps,

[symbolic/status]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[symbolic/devices]
Context=Devices
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/apps]
Context=Applications
Size=47
MinSize=8
MaxSize=512
Type=Scalable
